//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stuffort.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stuffort.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added:.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved ©.
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this subject? All the tasks will be deleted that connects to the subject!.
        /// </summary>
        internal static string AreYouSureDeleteSubject {
            get {
                return ResourceManager.GetString("AreYouSureDeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this task?.
        /// </summary>
        internal static string AreYouSureDeleteTask {
            get {
                return ResourceManager.GetString("AreYouSureDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to set the task as &apos;Completed&apos;?.
        /// </summary>
        internal static string AreYouSureDoneTask {
            get {
                return ResourceManager.GetString("AreYouSureDoneTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to set the task as &apos;Uncompleted&apos;?.
        /// </summary>
        internal static string AreYouSureUndoneTask {
            get {
                return ResourceManager.GetString("AreYouSureUndoneTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string ChooseSubject {
            get {
                return ResourceManager.GetString("ChooseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a subject.
        /// </summary>
        internal static string ChooseSubjectImproved {
            get {
                return ResourceManager.GetString("ChooseSubjectImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed tasks:.
        /// </summary>
        internal static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactPage {
            get {
                return ResourceManager.GetString("ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sessions:.
        /// </summary>
        internal static string CountOfSessions {
            get {
                return ResourceManager.GetString("CountOfSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of subjects:.
        /// </summary>
        internal static string CountOfSubjects {
            get {
                return ResourceManager.GetString("CountOfSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tasks:.
        /// </summary>
        internal static string CountOfTasks {
            get {
                return ResourceManager.GetString("CountOfTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline:.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer: Martin Bartos.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free timer:.
        /// </summary>
        internal static string FreeTimer {
            get {
                return ResourceManager.GetString("FreeTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string HoursL {
            get {
                return ResourceManager.GetString("HoursL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid!.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected subject is invalid!.
        /// </summary>
        internal static string InvalidSelectedSubject {
            get {
                return ResourceManager.GetString("InvalidSelectedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language has been set to: .
        /// </summary>
        internal static string LanguageSetTo {
            get {
                return ResourceManager.GetString("LanguageSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest session:.
        /// </summary>
        internal static string LongestSession {
            get {
                return ResourceManager.GetString("LongestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutesL {
            get {
                return ResourceManager.GetString("MinutesL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty!.
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must between 3-120 characters!.
        /// </summary>
        internal static string NameLengthOverFlow {
            get {
                return ResourceManager.GetString("NameLengthOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subject.
        /// </summary>
        internal static string NewSubject {
            get {
                return ResourceManager.GetString("NewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subject.
        /// </summary>
        internal static string NewSubjectPage {
            get {
                return ResourceManager.GetString("NewSubjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        internal static string NewTaskPage {
            get {
                return ResourceManager.GetString("NewTaskPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deadline.
        /// </summary>
        internal static string NoDeadline {
            get {
                return ResourceManager.GetString("NoDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stats available! Start a session first!.
        /// </summary>
        internal static string NoStats {
            get {
                return ResourceManager.GetString("NoStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any subjects.
        /// </summary>
        internal static string NoSubjects {
            get {
                return ResourceManager.GetString("NoSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any tasks.
        /// </summary>
        internal static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for the subject:.
        /// </summary>
        internal static string RenameSubject {
            get {
                return ResourceManager.GetString("RenameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for the task:.
        /// </summary>
        internal static string RenameTask {
            get {
                return ResourceManager.GetString("RenameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename subject.
        /// </summary>
        internal static string RenamingSubject {
            get {
                return ResourceManager.GetString("RenamingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename task.
        /// </summary>
        internal static string RenamingTask {
            get {
                return ResourceManager.GetString("RenamingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset the timer? Data will be deleted..
        /// </summary>
        internal static string ResetTimer {
            get {
                return ResourceManager.GetString("ResetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving timer.
        /// </summary>
        internal static string SavingTimer {
            get {
                return ResourceManager.GetString("SavingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        internal static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsL {
            get {
                return ResourceManager.GetString("SecondsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soon.
        /// </summary>
        internal static string Soon {
            get {
                return ResourceManager.GetString("Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatsPage {
            get {
                return ResourceManager.GetString("StatsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Timer.
        /// </summary>
        internal static string StudyTimerPage {
            get {
                return ResourceManager.GetString("StudyTimerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while deleting the subject!.
        /// </summary>
        internal static string SubjectErrorWhileDeleting {
            get {
                return ResourceManager.GetString("SubjectErrorWhileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while saving the subject!.
        /// </summary>
        internal static string SubjectErrorWhileSaving {
            get {
                return ResourceManager.GetString("SubjectErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        internal static string SubjectsPage {
            get {
                return ResourceManager.GetString("SubjectsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject has been successfully deleted!.
        /// </summary>
        internal static string SubjectSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SubjectSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject has been successfully renamed!.
        /// </summary>
        internal static string SubjectSuccessfullyRenamed {
            get {
                return ResourceManager.GetString("SubjectSuccessfullyRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject has been successfully saved!.
        /// </summary>
        internal static string SubjectSuccessfullySaved {
            get {
                return ResourceManager.GetString("SubjectSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve set this task as Completed. Congratulations!.
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while deleting the task!.
        /// </summary>
        internal static string TaskErrorWhileDeleting {
            get {
                return ResourceManager.GetString("TaskErrorWhileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while saving the task!.
        /// </summary>
        internal static string TaskErrorWhileSaving {
            get {
                return ResourceManager.GetString("TaskErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have at least one subject before adding a task!.
        /// </summary>
        internal static string TaskListCountIsZero {
            get {
                return ResourceManager.GetString("TaskListCountIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TasksPage {
            get {
                return ResourceManager.GetString("TasksPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been successfully deleted!.
        /// </summary>
        internal static string TaskSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("TaskSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been successfully renamed!.
        /// </summary>
        internal static string TaskSuccessfullyRenamed {
            get {
                return ResourceManager.GetString("TaskSuccessfullyRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been successfully saved!.
        /// </summary>
        internal static string TaskSuccessfullySaved {
            get {
                return ResourceManager.GetString("TaskSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve set this task as Uncompleted..
        /// </summary>
        internal static string TaskUncompleted {
            get {
                return ResourceManager.GetString("TaskUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have at least a minute in the timer to save it!.
        /// </summary>
        internal static string TimerAtLeast1Min {
            get {
                return ResourceManager.GetString("TimerAtLeast1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Timer is running!.
        /// </summary>
        internal static string TimerHasStartedNotification {
            get {
                return ResourceManager.GetString("TimerHasStartedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent:.
        /// </summary>
        internal static string TimerSpent {
            get {
                return ResourceManager.GetString("TimerSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer has started! Have a great time!.
        /// </summary>
        internal static string TimerStarted {
            get {
                return ResourceManager.GetString("TimerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer saved successfully!.
        /// </summary>
        internal static string TimerSuccessfullySaved {
            get {
                return ResourceManager.GetString("TimerSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task:.
        /// </summary>
        internal static string TimerTask {
            get {
                return ResourceManager.GetString("TimerTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted.
        /// </summary>
        internal static string Uncompleted {
            get {
                return ResourceManager.GetString("Uncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free timer.
        /// </summary>
        internal static string UndefinedSubject {
            get {
                return ResourceManager.GetString("UndefinedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a language!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
